APP_NAME = "AegisOS"
VERSION = "0.2.0"

MONITOR_INTERVAL = 1

PROCESS_LIMIT = 30

DATABASE_NAME = "aegisos.db"

CPU_WARNING_THRESHOLD = 80
CPU_CRITICAL_THRESHOLD = 90

CPU_CRITICAL_DURATION = 15

MEMORY_GROWTH_WARNING_MB = 20
MEMORY_GROWTH_CRITICAL_MB = 50

MEMORY_HISTORY_LENGTH = 30

THREAD_GROWTH_WARNING = 10
THREAD_GROWTH_CRITICAL = 25

INCIDENT_COOLDOWN = 30